name: CommandSyncBukkit
version: 1.1
description: Bukkit add-on for the BungeeCord plugin CommandSyncBungee.
author: YoFuzzy3
main: com.fuzzoland.CommandSyncBukkit.Main
dev-url: www.spigotmc.org/resources/commandsync.115

commands:
  Sync:
    description: Run commands across BungeeCord servers.

permissions:
  CommandSync.use:
    description: Access to the command /Sync.
    default: op